name: "Slugify value"
description: "Slugify a value"

inputs:
  value:
    description: "Value to be slugified"
    required: true
  slug-maxlength:
    description: "Max length of the slugified value"
    default: "29"
    required: true
outputs:
  value:
    description: "Value to be slugified"
    value: ${{ steps.slugify.outputs.value }}
  slug:
    description: "Slugified value"
    value: ${{ steps.slugify.outputs.slug }}
  slug-cs:
    description: "Slugified value (case-sensitive)"
    value: ${{ steps.slugify.outputs.slug-cs }}
  slug-url:
    description: "Slugified value url"
    value: ${{ steps.slugify.outputs.slug-url }}
  slug-url-cs:
    description: "Slugified value url (case-sensitive)"
    value: ${{ steps.slugify.outputs.slug-url-cs }}

runs:
  using: "composite"
  steps:
  - name: Slugify
    id: slugify
    shell: bash
    run: $GITHUB_ACTION_PATH/slugify.sh
    env:
      VALUE: ${{ inputs.value }}
      MAXLENGTH: ${{ inputs.slug-maxlength }}
